# Generated by Django 3.2.9 on 2021-12-01 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherJournal', '0002_auto_20211201_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='student',
            name='programing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teacherJournal.mark'),
        ),
    ]
