# Generated by Django 3.2.9 on 2021-12-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherJournal', '0006_auto_20211201_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='discrete_math_mark',
            field=models.CharField(choices=[('-', '-'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='-', max_length=127),
        ),
        migrations.AlterField(
            model_name='student',
            name='history_mark',
            field=models.CharField(choices=[('-', '-'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='-', max_length=127),
        ),
        migrations.AlterField(
            model_name='student',
            name='informatics_mark',
            field=models.CharField(choices=[('-', '-'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='-', max_length=127),
        ),
        migrations.AlterField(
            model_name='student',
            name='math_mark',
            field=models.CharField(choices=[('-', '-'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='-', max_length=127),
        ),
        migrations.AlterField(
            model_name='student',
            name='programing_mark',
            field=models.CharField(choices=[('-', '-'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='-', max_length=127),
        ),
    ]
